### ISSUE TITLE
VS Code Run Build Task expectations

### ISSUE THREAD

**Issue by huntc** [knurling-rs/test-embedded-app-example#1]
Thanks for providing this example project layout.

My expectation when running the build task in VS Code (menu: Terminal-Run Build Task) is that the source file in focus should be compiled. If I modify the cross/app/src/main.rs file and run the build task then I'm not seeing that it is compiled. However, I cd into the cross folder and `cargo build` from there then it will.

Any advice?

**Comment by huntc** [comment]
For myself, I've ended up creating a .vs_code/tasks.json file at the root level and ensured that builds perform on the board project (which I call my `app`):

```
        {
            /*
             * This is the default cargo build task,
             * but we need to provide a label for it,
             * so we can invoke it from the debug launcher.
             */
            "label": "Cargo Build (debug)",
            "type": "process",
            "command": "cargo",
            "args": [
                "build"
            ],
            "options": {
                "cwd": "app"
            },
            "problemMatcher": [
                "$rustc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            }
        },
```

Any changes made to the dependencies of my board project will automatically get pulled in still. Happy to provide a PR for you if this topic is of interest. Feel free to close the issue if not!

**Comment by japaric** [comment]
Hello @huntc

In general, we let [Rust-Analyzer](https://marketplace.visualstudio.com/items?itemName=matklad.rust-analyzer) (RA) compile check files instead of using VS code tasks like "Run Build Task". (RA compile checks (`cargo check`) files every time you save them and shows errors in the "Problem" tab, next to the "Terminal" tab, and also in the editor)

Is the goal here having a task to build *only* the firmware in release mode?

**Comment by huntc** [comment]
> Is the goal here having a task to build _only_ the firmware in release mode?

It is actually to mainly build the debug image so that I can flash it to a device. I'm going to close this issue though because what I've come to realise is that running the build task is more of a habit on my part, and not really required I guess. Thanks for the dialogue.
