### ISSUE TITLE
Build error: linker 'flip-link' not found

### ISSUE THREAD

**Issue by cpfister** [knurling-rs/test-embedded-app-example#2]
I cloned this repo and tried to build it. Unfortunately I got an error:

<img width="348" alt="Screenshot 2021-05-20 at 19 38 11" src="https://user-images.githubusercontent.com/1516153/119025902-e1dc0500-b9a4-11eb-9f5e-7cc2be8e907e.png">

Could it be that the configuration for probe-run is missing?

**Comment by hannobraun** [comment]
I think you need to `cargo install flip-link`, that should do it.

**Comment by cpfister** [comment]
Thanks, that was it!

**Comment by Urhengulas** [comment]
Thank you @hannobraun for answering! 

@cpfister: You can find the installation instruction here: https://github.com/knurling-rs/app-template
